### ISSUE TITLE
logging.debug/logging.info doesn't work as expected after importing fancylogger

### ISSUE THREAD

**Issue by boegel** [hpcugent/vsc-base#244] opened 2016-12-14 08:36 UTC
If the log level was set to debug (via `--debug` in a `GeneralOption` option parser), log messages emitted via `logging.debug` or `logging.info` are not there, even though the expectation is that they should.

The problem seems to be that the root logger is not a `FancyLogger` instance after importing `fancylogger`, but it should be?

```
>>> import logging
>>> from vsc.utils import fancylogger
>>> fancylogger.getLogger('foo')
<vsc.utils.fancylogger.FancyLogger object at 0x106b6b750>
>>> logging.getLogger()
<logging.RootLogger object at 0x106b37650>
```

**Comment by JensTimmerman** [comment] 2016-12-14 14:24
can you create a minimal script with the bug in it?

**Comment by JensTimmerman** [comment] 2016-12-14 14:30
Because it's not really clear to me what your bug report is?

Indeed, the fancylogger logger and the root logger are in a different namespace, this is by design as not to accedentally take over other loggers and not accedentaly start logging the logs of subpackages/dependencies. 

So if you mean: If I turn on debug using generaloption the logging of my dependencies is not appearing on the screen, the answer is: yes, this is by design.

**Comment by boegel** [comment] 2016-12-14 14:35
In that case: @stdweird: how is logging via `logging.debug` ever supposed to work?

Cfr. discussion in https://github.ugent.be/hpcugent/irun/pull/1/files/d357f19394723b98f7dd51603fe62c6de493f9f7#r5567

**Comment by JensTimmerman** [comment] 2016-12-14 16:28
There's 2 ways of fixing this:
-  have fancylogger set the global/root log level for all new logs created  (implemented in https://github.com/hpcugent/vsc-base/pull/245 )
- have generaloption set the global/root log level for all new logs created

option 2 will be a bit less invasive, but option 1 covers everything you would want everywhere.

**Comment by stdweird** [comment] 2016-12-14 16:36
@JensTimmerman the problem remains that the root logger is not a fancylogger, and in particular, that `logging.error/info/warn/...` do not use a fancylogger

i tought that was the whole point; we are actully using only `logging` in some modules

option 2 is more than enough imho

**Comment by JensTimmerman** [comment] 2016-12-14 16:47
that is true, if you want some fancy things like mpi ranks you need to still make a fancylogger, but by default logging should be enought.

option 2 implemented in https://github.com/hpcugent/vsc-base/pull/246

**Comment by stdweird** [comment] 2016-12-14 16:52
increasing the loglevel is not enough, also the handler incl format have to be adapted. eg the destination of the rootlogger has to be the same as the fancylogger, something i do not consider "fancy".

**Comment by JensTimmerman** [comment] 2017-01-30 17:38
should be fixed by https://github.com/hpcugent/vsc-base/pull/248

**Closed** 2017-01-31 16:39 UTC

**Comment by boegel** [comment] 2017-01-31 18:23
Confirmed (but requires `setroot()` or `SETROOTLOGGER = True` in the `GeneralOption` derivate (which is fine):

```
$ python -c "import logging; from vsc.utils import fancylogger; fancylogger.setroot(); print fancylogger.getLogger('foo'); print logging.getLogger()"
<vsc.utils.fancylogger.FancyLogger object at 0x107542310>
<vsc.utils.fancylogger.FancyRootLogger object at 0x1074e6490>
```
